module.exports = {
  metaDataFields: [
    "id",
    "name",
    "alternativeNames",
    "type",
    "state",
    "office",
    "latitude",
    "longitude",
    "county",
    "city",
    "contacts",
    "formattedAddress"],
  metaDataMapping:{
    id:'string',
    name:'string',
    alternativeNames:'array',
    type:'string',
    state:'string',
    city:'string',
    county:'string',
    formattedAddress:'string',
    contacts:'collection',
    office:'string / array',
    latitude:'float',
    longitude:'float',
  },
  necessaryFields: {
    all:[],
    Utility:[
      "id",
      "name",
      "type",
      "latitude",
      "longitude",
    ],
    City:["city","county","state"],
    County:[],
    ROC:[],
    State:[]
  },
  geocodeRelatedFields:[
    "city",
    "county",
    "state",
    "latitude",
    "longitude",
    "formattedAddress"
  ],
  descriptionsMap:{
    "servicePanelType:=:centerFed":"If Service Panel Type is Center-Fed",
    "systemSizeAc:>:10":"If AC System Size is Greater than 10",
    "assumedHigherBusOnStickerless:=:true":"If the Higher Bus was assumed when The Main Service Panel's Sticker was absent.",
    "usedCenterFedRule:=:false":"If The Center-Fed Rule was not used",
    "roofType:=:tile":"If The Roof Type is Tile",
    "roofType:=:compositeShingle":"If The Roof Type is Composite Shingle",
    "serviceElevation:>":"If The Elevation of The Service is Greater than",
    "loadCalculationCompleted:=:true":"If a Load Calculation was Completed",
    "faultStudyCompleted:=:true,loadCalculationCompleted:=:true":"If a Fault Study and a Load Calculation was Completed",
    "roofType:=:rolledComp":"If The Roof Type is Rolled Comp",
    "roofType:=:metalTrapezoidal":"If The Roof Type is Metal Trapezoidal",
    "roofType:=:metalStandingSeam":"If The Roof Type is Metal Standing Seam",
    "roofType:=:membrane":"If The Roof Type is Membrane",
    "roofType:=:tpo":"If The Roof Type is TPO",
    "roofType:=:epdm":"If The Roof Type is EPDM",
    "roofType:=:rubber":"If The Roof Type is Rubber",
    "roofType:=:foam":"If The Roof Type is Foam",
    "roofType:=:foam,mountingSystemType:=:ballast":"If The Roof Type is Foam and The Mounting System Type is Ballast",
    "roofType:=:silicone,mountingSystemType:=:ballast":"If The Roof Type is Silicone and The Mounting System Type is Ballast",
    "roofType:=:tar,mountingSystemType:=:ballast":"If The Roof Type is Tar and The Mounting System Type is Ballast",
    "mountingSystemType:=:ballast":"If The Mounting System Type is Ballast",
    "contractType:=:ppa":"If The Contract Type is PPA",
    "contractType:=:loan":"If The Contract Type is Loan",
    "contractType:=:pace":"If The Contract Type is PACE"
  }
};
