export default {
  database:{
    tableName:'',
    data:[],
    existingAhjs:[],
    createdAhjs:[],
    validation:{
      check:{
        ids:[],
        ruleId:null
      },
      results:{
        found:[],
        notFound:[],
        invalidExistence:[]
      }
    }
  },
  environment:{
    all:['dev','stage','prod'],
    map:{
      dev:{
        name:"Develop"
      },
      stage:{
        name:"Stage"
      },
      prod:{
        name:"Production"
      }
    },
    active:null
  },
  global:{
    processing:'',
    view:'metrics'
  },
  definitions:{
    tableName:'',
    rules:{},
    conditions:{},
    all:[]
  }
}
